#!/bin/bash
# Proxy time!
assignProxy(){
    PROXY_ENV="http_proxy HTTP_PROXY https_proxy HTTPS_PROXY ftp_proxy FTP_PROXY all_proxy ALL_PROXY no_proxy NO_PROXY VAGRANT_HTTP_PROXY VAGRANT_HTTPS_PROXY"
    for envar in $PROXY_ENV
    do
        export $envar=$1
    done
}
noproxy(){
    assignProxy ""
}
proxy(){
    if [ -n "$1" ]
    then
        proxy_value="$1"
    else
        #proxy_value="http://cis-americas-pitc-cinciz.proxy.corporate.ge.com:80"
        proxy_value="http://cis-americas-pitc-alphaz.proxy.corporate.ge.com:80"
    fi
    assignProxy $proxy_value
}
proxy
